CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "role" varchar,
  "city" varchar,
  "country" varchar,
  "dark_mode" varchar,
  "map_mode" varchar,
  "date_tolerance" varchar,
  "created_at" timestamp
);

CREATE TABLE "trips" (
  "trip_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "name" varchar,
  "created_at" timestamp
);

CREATE TABLE "trip_legs" (
  "trip_id" integer,
  "leg_no" integer,
  "mode" varchar,
  "origin_city" varchar,
  "destination_city" varchar,
  "leg_start" timestamp,
  "leg_stop" timestamp,
  "saved_at" timestamp,
  PRIMARY KEY ("trip_id", "leg_no")
);

CREATE TABLE "leg_flight" (
  "trip_id" integer,
  "leg_no" integer,
  "flight_id" varchar,
  "origin_airport" varchar,
  "destination_airport" varchar,
  PRIMARY KEY ("trip_id", "leg_no", "flight_id")
);

CREATE TABLE "country" (
  "country_key" varchar PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "city" (
  "city_key" varchar,
  "name" varchar,
  "country" varchar,
  "timezone" varchar,
  PRIMARY KEY ("city_key")
);

CREATE TABLE "airport" (
  "airport_key" varchar PRIMARY KEY,
  "city_key" varchar,
  "name" varchar
);

CREATE TABLE "airline" (
  "airline_id" varchar PRIMARY KEY,
  "name" varchar,
  "logo" varchar
);

CREATE TABLE "schedules" (
  "flight_id" varchar,
  "orig_airport" varchar,
  "dest_airport" varchar,
  "status" varchar,
  "dep_time" time,
  "arr_time" time,
  "airline" varchar,
  "planetype" varchar,
  "operates" varchar,
  "validity" varchar,
  PRIMARY KEY ("flight_id")
);

ALTER TABLE "trip_legs" ADD CONSTRAINT "trip_details" FOREIGN KEY ("trip_id") REFERENCES "trips" ("trip_id");

ALTER TABLE "leg_flight" ADD FOREIGN KEY ("trip_id", "leg_no") REFERENCES "trip_legs" ("trip_id", "leg_no");

ALTER TABLE "trips" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "city" ADD FOREIGN KEY ("country") REFERENCES "country" ("country_key");

ALTER TABLE "airport" ADD FOREIGN KEY ("city_key") REFERENCES "city" ("city_key");

ALTER TABLE "users" ADD FOREIGN KEY ("country") REFERENCES "country" ("country_key");

ALTER TABLE "users" ADD FOREIGN KEY ("city") REFERENCES "city" ("city_key");

ALTER TABLE "schedules" ADD FOREIGN KEY ("orig_airport") REFERENCES "airport" ("airport_key");

ALTER TABLE "leg_flight" ADD FOREIGN KEY ("origin_airport") REFERENCES "airport" ("airport_key");

ALTER TABLE "leg_flight" ADD FOREIGN KEY ("destination_airport") REFERENCES "airport" ("airport_key");

ALTER TABLE "leg_flight" ADD FOREIGN KEY ("flight_id") REFERENCES "schedules" ("flight_id");

ALTER TABLE "schedules" ADD FOREIGN KEY ("dest_airport") REFERENCES "airport" ("airport_key");

ALTER TABLE "schedules" ADD FOREIGN KEY ("airline") REFERENCES "airline" ("airline_id");
